language: node_js

services: docker

env: 
    - DOCKER_COMPOSE_VERSION=1.23.2

before_install:    

install: 
    - docker-compose -f docker-compose-build.yml build

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push gddccc/udagram-api-user:v1
  - docker push gddccc/udagram-api-feed:v1
  - docker push gddccc/udagram-frontend:v1
  - docker push gddccc/reverseproxy:v1
  